var source = new UnityEngine.Texture2D(2,2,UnityEngine.TextureFormat.RGBA32,false);
source.LoadImage(System.IO.File.ReadAllBytes("Assets/ArtSource/EdelzioBackpackUserDirectionsV2.png"));
if(source.width!=1024 || source.height!=512) throw new System.Exception("Expected the user's eight-view 1024x512 sheet");
var atlas=new UnityEngine.Texture2D(256,128,UnityEngine.TextureFormat.RGBA32,false);
for(int y=0;y<128;y++)for(int x=0;x<256;x++)atlas.SetPixel(x,y,source.GetPixel(x*4+2,y*4+2));
atlas.Apply();
const string path="Assets/Resources/Varginha/Equipment/EdelzioBackpackUserDirectionsV2.png";
UnityEditor.AssetDatabase.ReleaseCachedFileHandles();
System.IO.File.WriteAllBytes(path,atlas.EncodeToPNG());
UnityEditor.AssetDatabase.ImportAsset(path,UnityEditor.ImportAssetOptions.ForceSynchronousImport);
var importer=(UnityEditor.TextureImporter)UnityEditor.AssetImporter.GetAtPath(path);
importer.textureType=UnityEditor.TextureImporterType.Default;importer.isReadable=true;
importer.filterMode=UnityEngine.FilterMode.Point;importer.mipmapEnabled=false;
importer.textureCompression=UnityEditor.TextureImporterCompression.Uncompressed;
importer.npotScale=UnityEditor.TextureImporterNPOTScale.None;importer.wrapMode=UnityEngine.TextureWrapMode.Clamp;
importer.SaveAndReimport();
UnityEditor.AssetDatabase.ImportAsset("Assets/ArtSource/EdelzioBackpackUserDirectionsV2.png");
UnityEngine.Object.DestroyImmediate(source);UnityEngine.Object.DestroyImmediate(atlas);
return "User's sheet imported at its native 64-pixel cells, source preserved";
